name: hearpreprocess

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
#        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: apt-get
      run: |
        sudo apt-get update
        # ffmpeg >= 4.2 for focal ubuntu
        sudo apt-get install -y libsndfile-dev ffmpeg
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        # hear2021-secret-tasks will be a submodule of hear-preprocess,
        # so we don't need:
        #   pip install -e ".[test]"
        git clone https://github.com/neuralaudio/hear-preprocess.git
        # Remove the already existing secret tasks directory
        rm -Rf hear-preprocess/hearpreprocess/secrettasks/
        ln -s `pwd` hear-preprocess/hearpreprocess/secrettasks
        cd hear-preprocess && pip install -e ".[dev]"
    - name: Integration test
      run: |
        cd hear-preprocess && python3 -m hearpreprocess.runner all-secret --mode small
